version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: happygear
      MYSQL_DATABASE: happygear
    volumes:
       - mysql:/data/mysql
    ports:
      - "3306:3306"

  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: SA@12345
      ACCEPT_EULA: Y
    volumes:
      - sql-server:/data/sql-server
    ports:
      - "1433:1433"

  api-server:
    container_name: api-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: unless-stopped
  
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    ports:
     - "8081:80"
volumes:
  mysql:
  sql-server:
  nginx:
  api-server: