spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/happygear
    username: root
    password: happygear
  flyway:
    enabled: true
    locations: classpath:db/migration/{vendor}
    baselineOnMigrate: true
